trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:
- stage: SetupEnvironment
  jobs:
  - job: SetupChromeDriver
    steps:
    - powershell: |
        # Download and install ChromeDriver
        $chromeDriverVersion = '118.0.5993.70'
        $chromeDriverZip = "$(Agent.ToolsDirectory)\chromedriver.zip"
        $chromeDriverDir = "$(Agent.ToolsDirectory)\chromedriver"

        Invoke-WebRequest -Uri "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$($chromeDriverVersion)/win64/chromedriver-win64.zip" -OutFile $chromeDriverZip
        Expand-Archive -Path $chromeDriverZip -DestinationPath $chromeDriverDir
        Remove-Item $chromeDriverZip
      displayName: 'Install ChromeDriver'

- stage: BuildAndTest
  jobs:
  - job: Build
    steps:
    - checkout: self

    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'test'
        options: '-Dsurefire.suiteXmlFiles=testng.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: CopyFiles@2
      displayName: 'Copy ExtentReport Files'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**/ExtentReport/**'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: CopyFiles@2 
      displayName: 'Copy Screenshots'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)/ScreenShot'
        Contents: '**/*.png'
        TargetFolder: '$(build.artifactstagingdirectory)/ScreenShot'

    - task: CopyFiles@2
      displayName: 'Copy Emailable Report'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)/target/surefire-reports'
        Contents: 'emailable-report.html'
        TargetFolder: '$(build.artifactstagingdirectory)/EmailableReport'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
