trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: SetEnvironmentVariables
    jobs:
    - job: SetVariables
      steps:
        - script: |
            export BROWSER=chrome
          displayName: 'Set BROWSER environment variable'

  - stage: CheckChromeVersion
    jobs:
    - job: CheckChrome
      steps:
      - script: |
          # Check Chrome version
          google-chrome --version
        displayName: 'Check Chrome Version'

  - stage: BuildAndTest
    jobs:
    - job: BuildAndTest
      steps:
        - checkout: self

        - script: |
            # Your other build steps go here (e.g., Maven build, compilation, etc.)
          displayName: 'Other Build Steps'

        - script: |
            # Set the execution environment to "azure" as an environment variable
            echo "EXECUTION_ENVIRONMENT=azure" >> $(Agent.BuildDirectory)/.env
            source $(Agent.BuildDirectory)/.env

            # Run your tests using Maven (replace with the actual test execution command)
            mvn test
          displayName: 'Run Unit Tests'

  - stage: PublishArtifacts
    jobs:
    - job: Publish
      steps:
        - task: PublishBuildArtifacts@1
          inputs:
            pathtoPublish: '$(System.DefaultWorkingDirectory)'
            artifactName: 'MyJavaArtifacts'
