trigger:
- master

pool:
  vmImage: 'windows-latest' # Change the VM image to a Windows agent

stages:
  - stage: CheckoutCode
    jobs:
    - job: 'Checkoutgitcode'
      steps:
        - checkout: self

  - stage: BuildAndTest
    jobs:
    - job: Build
      steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean install'

    - job: UnitTests
      steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'test'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'

    - job: InstallGeckoDriver
      steps:
        - script: |
            # Download and install GeckoDriver
            Invoke-WebRequest -Uri 'https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-win64.zip' -OutFile 'geckodriver.zip'
            Expand-Archive -Path 'geckodriver.zip' -DestinationPath '$env:USERPROFILE\.m2\repository\webdriver\geckodriver\win64\0.30.0'
            Remove-Item 'geckodriver.zip'
          displayName: 'Install GeckoDriver'

  - stage: CodeAnalysis
    jobs:
    - job: CodeAnalysis
      steps:
        - script: |
            # Add commands for code analysis (e.g., SonarQube)
          displayName: 'Code Analysis'

  - stage: Deploy
    jobs:
    - job: DeployToStaging
      steps:
        - script: |
            # Add commands to deploy to your staging environment
          displayName: 'Deploy to Staging'

  # Add more stages for other deployment environments as needed

  - stage: PublishArtifacts
    jobs:
    - job: Publish
      steps:
        - task: PublishBuildArtifacts@1
          inputs:
            pathtoPublish: '$(System.DefaultWorkingDirectory)'
            artifactName: 'MyJavaArtifacts'
