trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:
- stage: BuildAndTest
  jobs:
  - job: Build
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'


    - checkout: self

- stage: BuildAndTest
  jobs:
  - job: Build
    steps:
    - checkout: self
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'test'
        options: 'test -Dsurefire.suiteXmlFiles=testng.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false


    - task: CopyFiles@2
      displayName: 'Copy ExtentReport Files'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**/ExtentReport/**'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: CopyFiles@2 
      displayName: 'Copy Screenshots'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)/ScreenShot'
        Contents: '**/*.png'
        TargetFolder: '$(build.artifactstagingdirectory)/ScreenShot'

    - task: CopyFiles@2
      displayName: 'Copy Emailable Report'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)/target/surefire-reports'
        Contents: 'emailable-report.html'
        TargetFolder: '$(build.artifactstagingdirectory)/EmailableReport'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
