trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:
- stage: SetupEnvironment
  jobs:
  - job: SetupChromeDriver
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Download and install ChromeDriver
          Invoke-WebRequest -Uri 'https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.94/win64/chromedriver-win64.zip' -OutFile 'chromedriver.zip'
          Expand-Archive -Path 'chromedriver.zip' -DestinationPath '$(Agent.ToolsDirectory)\chromedriver'
          Remove-Item 'chromedriver.zip'
      displayName: 'Install ChromeDriver'

- stage: BuildAndTest
  jobs:
  - job: Build
    timeoutInMinutes: 120 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 45 # how much time to give 'run always even if cancelled tasks' before stopping them
    steps:
    - checkout: self
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'test'
        options: 'test -Dsurefire.suiteXmlFiles=testng.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: CopyFiles@2 
      displayName: 'Copy ExtentReport Files'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**/ExtentReport/**'
        TargetFolder: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()

    - task: CopyFiles@2 
      displayName: 'Copy Screenshots to: $(build.artifactstagingdirectory)/ScreenShot'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)/ScreenShot'
        Contents: '**/*.png'
        TargetFolder: '$(build.artifactstagingdirectory)/ScreenShot'
      condition: succeededOrFailed()

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()
