trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: SetEnvironmentVariables
    jobs:
    - job: SetVariables
      steps:
        - script: |
            export BROWSER=chrome
          displayName: 'Set BROWSER environment variable'

  - stage: BuildAndTest
    jobs:
    - job: BuildAndTest
      steps:
        - checkout: self

        - script: |
            # Your other build and test steps go here
          displayName: 'Other Build and Test Steps'

  - stage: PublishArtifacts
    jobs:
    - job: Publish
      steps:
        - task: PublishBuildArtifacts@1
          inputs:
            pathtoPublish: '$(System.DefaultWorkingDirectory)'
            artifactName: 'MyJavaArtifacts'
